main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

project_azima/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    if request.method == 'POST':
        masukx = int(request.POST['titik x'])
        masuky = int(request.POST['titik y'])
        pusatx = int(request.POST['pusat x'])
        pusaty = int(request.POST['pusat y'])
        k = int(request.POST['skala'])
        keluarx = k*(masukx-pusatx)+pusatx
        keluary = k*(masuky-pusaty)+pusaty
        keluar = [str(keluarx) + ',' + str(keluary)]
        context = {'keluar': keluar,
                   }
        return render(request, 'main/home.html', context)

    else:
        return render(request, 'main/home.html', {})

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pemograman Lanjut</title>
{% endblock meta %}

{% block content %}
<header>
    <div class="container d-flex justify-content-between align-items-center">
        <div id="logo">
            <h7>
                <p1 style="font-weight: bolder">Pemograman Lanjut - Perhitungan Transformasi Dilatasi</p1>
            </h7>
        </div>

        <!-- .navbar -->
    </div>
</header>
<!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero">
    <div class="card" data-aos="zoom-out">
        <div class="row">
            <div class="column" style="margin-top: auto; margin-bottom: auto">
                <table style="color: black">
                    <tr>
                    <td style="width: 200px; vertical-align:top">
                        Nama<br>
                        NIM<br>
                        Jurusan<br>
                        Fakultas<br>
                        email<br>
                    </td>
                    <td style="width:10px; vertical-align:top">
                        :<br>
                        :<br>
                        :<br>
                        :<br>
                        :<br>
                    </td>
                    <td style="width:400px; vertical-align:top">
                        Azimatul Matsniya<br>
                        181810101064<br>
                        Matematika<br>
                        Fakultas Matematika dan Ilmu Pengetahuan Alam<br>
                        azimatulmatsniya@gmail.com<br>
                    </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>
<form method="post">
    {% csrf_token %}
    <table style="color: black">
        <tr>
        <td style="width:350px; vertical-align:top">
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Titik x </label>
        <input type="text" class="form-control" id="formGroupExampleInput1" placeholder="Input nilai x dari titik yang akan didilatasi"
               name="titik x">
    </div>
     <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Titik y</label>
        <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Input nilai y dari titik yang akan didilatasi"
               name="titik y">
    </div>
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Skala Dilatasi</label>
        <input type="text" class="form-control" id="formGroupExampleInput3" placeholder="Input Skala Dilatasi"
               name="skala">
    </div>
        </td>
        <td style="width:350px; vertical-align:top">
     <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Pusat Dilatasi x</label>
        <input type="text" class="form-control" id="formGroupExampleInput4" placeholder="Input nilai x dari titik pusat dilatasi"
               name="pusat x">
    </div>
     <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Pusat Dilatasi y</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Input nilai y dari titik pusat dilatasi"
               name="pusat y">
    </div>
        </td>
        </tr>
        <tr>
            <td style="width:350px; vertical-align:top">
    <button type="submit" class="btn btn-success">Cek Hasil</button>
        </td></tr>
        <tr>
            <td style="width:350px; vertical-align:top">
    <div class="mb-3">
        <label for="formGroupExampleOutput2" class="form-label">Titik Hasil Dilatasi</label>
        <output type="text" class="form-control" id="formGroupExampleOutput2" name="keluar">{{keluar}}</output>
    </div>
            </td>
        </tr>
    </table>
</form>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block meta %}
    {% endblock meta %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" ><img
                src="http://kemahasiswaan.unej.ac.id/wp-content/uploads/2020/07/cropped-Logo-Baku-UNEJ-2020-Square.png"
                style="height: 25pt;"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
                </li>

            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<br>

<div class="container">
    {% block content %}
    {% endblock content %}

</div>

<footer>
    <p>Hubungi <a href="https://wa.me/qr/E6CJBVJPLZ6WE1">Contact person</a> untuk info lebih lanjut
        <marquee
        ><strong
        ><img
                src="http://kemahasiswaan.unej.ac.id/wp-content/uploads/2020/07/cropped-Logo-Baku-UNEJ-2020-Square.png"
                style="height: 13pt;"/>
            | UAS AZIMA - Pemrograman Lanjut</strong
        ></marquee
        >
</footer>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>